### ISSUE TITLE
Verbesserungsvorschläge

### ISSUE THREAD

**Issue by robinp456** [wm75/PM-21_2018#2]
Hallo, das sind meine Verbesserungsvorschläge:

[Aufgabe1.txt](https://github.com/wm75/PM-21_2018/files/1942855/Aufgabe1.txt)

- Es gibt eine perfekte Strategie ,sodass man das spiel immer gewinnt (je nachdem ob man anfängt oder 
   nicht) diese könnte man dann noch etwas abschwächen (z.B. dass Programm wählt nur zu 50% den 
   perfekten Zug) und implementieren.

- Das Programm gibt einen Fehler bei nicht Zahl eingaben aus, diesen könnte man z.B. mit einem try 
   except statement abfangen

- Man könnte die Siegcondition (>100) und die Schritte in denen man hochzählt auch zufällig auswählen, 
  dann müsste man wieder neu überlegen wieviel man addieren sollte --> abwechslungsreicher

- Man könnte anstatt gegen den Computer zu spielen einen 2. Spieler implementieren

Die ersten 2 Punkte habe ich im Anhang implementiert.

**Comment by wm75** [comment]
Sehr schön bearbeitet!

Weil Du Dich ja schon auskennst, hier schon mal etwas detaillierteres/kritischeres feedback:

- Deine Implementierung der Gewinnstrategie ist sehr elegant, lässt den Computer aber im Zweifelsfall die Regeln brechen, um zu gewinnen. Kannst Du den entsprechenden Fehler finden und beheben?
- ein nacktes ``except`` in einem ``try``/``except``-Block ist eigentlich fast immer schlecht:
  Das Problem damit ist, dass dann **alle** Fehler abgefangen werden, auch solche, die man nicht vorhergesehen hat, z.B. Syntax- und andere Programmierfehler. Das macht das debugging von solchem Code sehr unangenehm, weil man keine saubere Fehlerbeschreibung mit traceback von Python bekommt, sondern eben nur seltsamen Programmfluß.
  Prinzipiell ist es deshalb besser speziell den Typ Fehler abzufangen, den man auch behandeln will,
  in diesem Fall mittels ``except ValueError:``, und nur genau den Code abzusichern, der den Fehler produzieren kann - in diesem Fall die eine Zeile mit der ``int()``-Umwandlung.

**Comment by robinp456** [comment]
- Ah stimmt da fehlt noch eine Abfrage für x==0 wenn der Spieler am gewinnen ist., sonst addiert der Computer um 0

- Ja, der value Error ist natürlich die schönere Lösung
[Aufgabe1.txt](https://github.com/wm75/PM-21_2018/files/1943108/Aufgabe1.txt)
